/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import net.proteanit.sql.DbUtils;
import package2.DB.Db;
import package2.DB.Query;

/**
 *
 * @author VALLABH KULKARNI
 */
public class AddToCart extends javax.swing.JFrame {

  
	/**
     * Creates new form AddToCart
     */
	public String Customer_name;
    public AddToCart(String name) {
        initComponents();
        Customer_name=name; 
        jLabel1.setText(name);
        Bill_list();
    } 
    public AddToCart() 
    { 
    	 initComponents();
    }

    

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("CUSTOMER NAME ");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 153));
        jLabel13.setText("Product Id ");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("Quantity");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(153, 0, 153));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 0, 153));
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("CUSTOMER NAME : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Id ", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 153));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 153));
        jLabel15.setText("PRODUCT ID");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 153));
        jLabel16.setText("QUANTITY");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 153));
        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 0, 153));
        jButton8.setText("UPDATE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                                                                                             ");

        jButton3.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 153));
        jButton3.setText("PAY NOW !");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("INVOICE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(269, 269, 269))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(114, 114, 114)
                        .addComponent(jButton6)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(this,"Bill Processing is Running"); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    	System.out.println("1");
    }//GEN-LAST:event_jButton4ActionPerformed
 
    public int Delete_product() 
    { 
    	try {
            Connection conn=Db.Connect();    
            String query=Query.Delete_customer_product;
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setInt(1,Integer.valueOf(jTextField6.getText()));
            
            ResultSet rs=stm.executeQuery();
            
            rs.next(); 
            int no_of_product=rs.getInt(1);
            conn.close();
            return no_of_product;
                
    	}
       catch (SQLException e) {
      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
      	 return 0;
       } 
    }
    public void Update_product(Integer product,Integer Id) 
	{ 
		try {
            Connection conn=Db.Connect();    
            String query=Query.Customer_product_play;
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setInt(1,product);
            stm.setInt(2,Id);
            stm.execute();
            conn.close();     
    	}
       catch (SQLException e) {
      	 JOptionPane.showMessageDialog(this,"No Inftion" +e.getMessage()); 	 
       } 
	}
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here: 
    	Update_product(Delete_product(),Integer.valueOf(jTextField6.getText()));
    	try {
            Connection conn=Db.Connect();    
            String query=Query.Customerlist_delete;
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setInt(1,Integer.valueOf(jTextField6.getText()));
            stm.execute();
            Bill_list();
            conn.close();     
    	}
       catch (SQLException e) {
      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
      	 
       } 
    }//GEN-LAST:event_jButton6ActionPerformed 

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    	System.out.println("a");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         if( jTextField6.getText().isEmpty() ||  jTextField7.getText().isEmpty())
{   
	JOptionPane.showMessageDialog(this,"Missing Information"); 
} 
else 
{ 
	    try 
	    { 
	    	Connection conn=Db.Connect();    
            String query=Query.Customer_bill_update;
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setInt(1,Integer.valueOf(jTextField6.getText()));
            ResultSet rs=stm.executeQuery();
            rs.next();
            int Quantity1=rs.getInt(1); 
            int Quantity2=Integer.valueOf(jTextField7.getText());
            System.out.println(Quantity1  + "  " + Quantity2);
            if(Quantity1 > Quantity2)
            { 
            	
            	add_product(Quantity1,Quantity2); 
            	int final_price=Quantity2*Price(jTextField6.getText());
            	update_product1(Quantity2,final_price);
            	 Bill_list();
            }
            else 
            	
            { 
            
            	 if(check_product_bill(Quantity1,Quantity2))
            	 { 
            		  
            		  play1(Quantity1,Quantity2); 
            		  int final_price=Quantity2*Price(jTextField6.getText());
            		  update_product1(Quantity2,final_price);
            	 }
            	 else 
            	 {
            		 JOptionPane.showMessageDialog(this,"Quantity is less");   
            	 }
            }
	    }
	    catch (SQLException e) {
	      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
	      	 
	       } 
}
    
    }//GEN-LAST:event_jButton8ActionPerfrmed
  
	private int Price(String text) {
		// TODO Auto-generated method stub
   	 try 
	    { 
	    	Connection conn=Db.Connect();    
         String query="Select Product_price from Product where Product_id = ? ";
         PreparedStatement stm=conn.prepareStatement(query);
         stm.setInt(1,Integer.valueOf(jTextField6.getText()));
         ResultSet rs=stm.executeQuery();
         rs.next(); 
         int price = rs.getInt(1);
         return price;
	    }
	    catch (SQLException e) {
	      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
	      	 return 0;
	      
	       
	    }
	}
	private void play1(int q1,int q2) {
		// TODO Auto-generated method stub
    	 try 
    	    { 
    	    	Connection conn=Db.Connect();    
                String query=Query.Customer_bill_update5;
                PreparedStatement stm=conn.prepareStatement(query);
                stm.setInt(1,q2-q1);
                stm.setInt(2,Integer.valueOf(jTextField6.getText()));
                stm.execute();
                  	
    	    }
    	    catch (SQLException e) {
    	      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
    	      
    	       }
	}
	private Boolean check_product_bill(int quantity1, int quantity2) {
		// TODO Auto-generated method stub
    	 try 
   	    { 
   	    	  Connection conn=Db.Connect();    
               String query=Query.Customer_bill_update3;
               PreparedStatement stm=conn.prepareStatement(query);
               stm.setInt(1,Integer.valueOf(jTextField6.getText()));
               ResultSet rs=stm.executeQuery();
               rs.next(); 
               int quantity3=rs.getInt(1);
               if(quantity3>=(quantity2-quantity1)) 
               {
            	    return  true;
               }
               else 
               {
            	    return false;
               }
    	
   	    }
   	    catch (SQLException e) {
   	      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
   	      	 return false;
   	       }
	}
	private void update_product1(int q,int price) {
		// TODO Auto-generated method stub
    	 try 
  	    { 
  	    	Connection conn=Db.Connect();    
              String query=Query.Customer_bill_update2;
              PreparedStatement stm=conn.prepareStatement(query);
              stm.setInt(1,q);
              stm.setInt(2,price);
              stm.setInt(3,Integer.valueOf(jTextField6.getText()));
              stm.execute(); 
              System.out.println("Update is done in customer_table");
  	    }
  	    catch (SQLException e) {
  	      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
  	      	 
  	       } 
	}
	private void add_product(int q1,int q2) {
    	 try 
 	    { 
 	    	Connection conn=Db.Connect();    
             String query=Query.Customer_bill_update1;
             PreparedStatement stm=conn.prepareStatement(query);
             stm.setInt(1,q1-q2);
             stm.setInt(2,Integer.valueOf(jTextField6.getText()));
             stm.execute();
             System.out.println("Update is done in product_table");
 	    }
 	    catch (SQLException e) {
 	      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
 	      	 
 	       } 
		// TODO Auto-generated method stub
		
	}
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    	new Customer(Customer_name).setVisible(true);
    	dispose();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    	
    	try {
            Connection conn=Db.Connect();    
            String query=Query.Customer_final_bill;
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setString(1,Customer_name);
           
            ResultSet rs=stm.executeQuery();
            rs.next();
            int final_bill=rs.getInt(1);
            JOptionPane.showMessageDialog(this,"Your Total Bill is : " + final_bill ); 
            JOptionPane.showMessageDialog(this,"Thank You");  
            Manage_product.Manage_customer(Customer_name);
            new UserIdentity().setVisible(true);
            dispose();
            conn.close();     
    	}
       catch (SQLException e) {
      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
      	 
       } 
    }//GEN-LAST:event_jButton3ActionPerformed
    

    private void Customer_delete() {
		// TODO Auto-generated method stub
    	try {
            Connection conn=Db.Connect();    
            String query=Query.Customer_final_delete;
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setString(1,Customer_name);
            stm.execute();
            conn.close();     
    	}
       catch (SQLException e) {
      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
      	 
       } 
	}

	private void Bill_list() 
    {
    	try {
            Connection conn=Db.Connect();    
            String query=Query.Customerlist_search;
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setString(1,Customer_name);
            ResultSet rs=stm.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            conn.close();     
    	}
       catch (SQLException e) {
      	 JOptionPane.showMessageDialog(this,"No Information" +e.getMessage()); 
      	 
       } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddToCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
